import Head from "next/head";
import { ReactNode } from "react";

import styles from "@/styles/layout.module.css";

export default function Layout({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <>
      <Head>
        <title>{title ? title : "Generador de plantillas"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.webp" />
      </Head>
      <header className={styles.div_title}>
        <h1 className={styles.title}>Generador de plantillas</h1>
      </header>
      <main className={styles.container}>{children}</main>
    </>
  );
}
